### ISSUE TITLE
Gpt.Partition.make ~type_guid argument should be Uuidm.t

### ISSUE THREAD

**Issue by reynir** [mirage/ocaml-gpt#5]
https://github.com/PizieDust/ocaml-gpt/blob/e2c6f75c1bc92a955b317fcb0b889ac2f2c6406d/lib/gpt.ml#L30
If we make the `type_guid` argument of `Gpt.Partition.make` a `Uuidm.t` instead of a string we can skip the UUID parsing in the function.

**Comment by PizieDust** [comment]
Thank you for pointing this out. With this, the test that checks for a wrong `type_guid` becomes obsolete as the type itself is a `uuidm.t` value and should fail if something is passed in which is not it
